# Generated by Django 5.2.3 on 2025-06-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('features', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
