# Generated by Django 5.2.3 on 2025-06-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='category',
            field=models.CharField(choices=[('small', 'Small Business Solutions'), ('large', 'Large Business Solutions'), ('other', 'Other Printing Solutions')], default='small', max_length=10),
        ),
    ]
