# Generated by Django 5.0.7 on 2025-06-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerapp', '0002_printer_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('location', models.CharField(max_length=200)),
                ('project_link', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
