# Generated by Django 5.0.7 on 2025-07-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerapp', '0003_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('product_type', models.CharField(choices=[('printer', 'Printer'), ('ip_phone', 'IP Phone'), ('it_solution', 'IT Solution'), ('networking', 'Networking'), ('parrot', 'Parrot'), ('solar', 'Solar')], max_length=20)),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
