# Generated by Django 5.0.7 on 2025-08-06 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printerapp', '0007_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
