# Generated by Django 5.0.7 on 2025-08-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerapp', '0009_remove_order_user_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
