# Generated by Django 5.2.3 on 2025-08-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerapp', '0010_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
