# Generated by Django 5.0.7 on 2025-09-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerapp', '0011_slide_image_alter_slide_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('department', models.CharField(choices=[('office_printer', 'Office Printer Department'), ('solar', 'Solar Department'), ('it', 'IT Department')], max_length=20)),
            ],
        ),
    ]
